import assert from 'node:assert/strict';
import {parseEntryId,buildDemoSquad,freshnessText,validatePlannerData} from '../assets/planner-onboarding.mjs';
assert.equal(parseEntryId('218806'),218806);
assert.equal(parseEntryId(' https://fantasy.premierleague.com/entry/218806/event/5 '),218806);
for(const bad of ['0','-1','1e3','100000001','https://evil.test/entry/123','https://fantasy.premierleague.com.evil.test/entry/123']) assert.equal(parseEntryId(bad),null);
const players=Array.from({length:80},(_,i)=>({id:i+1,element_type:1+Math.floor(i/20),team:1+i%10,status:'a',now_cost:40+i%10,total_points:i}));
const demo=buildDemoSquad(players);
assert.equal(demo.picks.length,15);assert.equal(new Set(demo.picks.map(p=>p.element)).size,15);
const map=new Map(players.map(p=>[p.id,p]));
const squad=demo.picks.map(p=>map.get(p.element));
assert.deepEqual([1,2,3,4].map(t=>squad.filter(p=>p.element_type===t).length),[2,5,5,3]);
assert.deepEqual([1,2,3,4].map(t=>squad.slice(0,11).filter(p=>p.element_type===t).length),[1,4,4,2]);
assert.ok([...new Set(squad.map(p=>p.team))].every(t=>squad.filter(p=>p.team===t).length<=3));
assert.ok(demo.entry_history.bank>=0);
assert.equal(demo.entry_history.bank+squad.reduce((s,p)=>s+p.now_cost,0),1000);
assert.equal(demo.picks.filter(p=>p.is_captain && p.position<=11).length,1);
assert.equal(demo.picks.filter(p=>p.is_vice_captain && p.position<=11).length,1);
assert.deepEqual(buildDemoSquad([...players].reverse()),demo);
assert.throws(()=>buildDemoSquad([]));
assert.throws(()=>validatePlannerData({},[]));
const status={demo:false,sourceGw:5,activeGw:6,fetchedAt:1000,now:121000};
assert.equal(freshnessText(status),'Squad from GW5 deadline · Data fetched 2 minutes ago · Viewing GW6');
assert.match(freshnessText({...status,failed:true}),/Refresh failed/);
assert.match(freshnessText({...status,demo:true}),/^Demo squad/);
console.log('Onboarding tests passed: URL validation, legal deterministic demo, budget, captaincy and freshness.');
